services:
  web:
    build:
      context: .
      args:
        CACHEBUST: ${CACHEBUST:-1}
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
