services:
  mqtt:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    networks:
      - dokploy-network

volumes:
  mqtt-data:
  mqtt-log:

networks:
  dokploy-network:
    external: true
